apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-repo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-repo-web
  template:
    metadata:
      labels:
        app: test-repo-web
    spec:
      serviceAccountName: web-sa
      containers:
      - name: web
        image: tatianail05/repo-web:latest
        ports:
        - containerPort: 80